import { CodeReviewResult } from '../types';

/**
 * Generates a clean, comprehensive Markdown report from a CodeReviewResult
 */
export function generateMarkdownReport(result: CodeReviewResult): string {
  const dateStr = new Date(result.timestamp || Date.now()).toUTCString();
  const severityBadge = (sev: string) => {
    switch (sev.toLowerCase()) {
      case 'critical': return '🔴 CRITICAL';
      case 'high': return '🟠 HIGH';
      case 'medium': return '🟡 MEDIUM';
      case 'low': return '🔵 LOW';
      default: return '⚪ INFO';
    }
  };

  let md = `# Code Review Audit Report

> Generated by **The 24/7 Intelligent Code Reviewer**  
> Engine: **ANN AST Classifier & Vertex AI Gemini Flash Lite**  
> Generated at: \`${dateStr}\`

---

## 1. Executive Summary

| Attribute | Value |
|:---|:---|
| **Target File** | \`${result.filename || 'source_code'}\` |
| **Language** | \`${result.language || 'auto'}\` |
| **Commit Hash** | \`${result.commitHash || 'latest'}\` |
| **Branch / PR** | \`${result.branch || 'main'}\` ${result.prNumber ? `(PR #${result.prNumber})` : ''} |
| **Author** | \`${result.author || 'developer'}\` |
| **Quality Grade** | **${result.rating?.letterGrade || 'N/A'}** (${result.rating?.overallScore ?? 0}/100) |
| **Verdict** | **\`${result.rating?.verdict || 'REVIEW_PENDING'}\`** |

### Overview
${result.summary?.headline ? `**${result.summary.headline}**\n\n` : ''}${result.summary?.overview || 'Review completed successfully.'}

${result.summary?.suggestedAction ? `**Suggested Action:** ${result.summary.suggestedAction}\n` : ''}
${result.summary?.timeSavedMinutes ? `*Estimated Engineering Time Saved: ~${result.summary.timeSavedMinutes} minutes*\n` : ''}

---

## 2. Quality & Security Scores

| Category | Score | Status |
|:---|:---:|:---|
| **Overall Score** | **${result.rating?.overallScore ?? 0} / 100** | ${result.rating?.overallScore >= 80 ? '✅ High Quality' : result.rating?.overallScore >= 60 ? '⚠️ Acceptable with warnings' : '❌ Needs Improvement'} |
| **Security & Vulnerability** | ${result.rating?.securityScore ?? 0} / 100 | ${result.rating?.securityScore >= 80 ? 'Shielded' : 'Vulnerabilities detected'} |
| **Performance & Latency** | ${result.rating?.performanceScore ?? 0} / 100 | ${result.rating?.performanceScore >= 80 ? 'Optimized' : 'Bottlenecks identified'} |
| **Maintainability & Clean Code** | ${result.rating?.maintainabilityScore ?? 0} / 100 | ${result.rating?.maintainabilityScore >= 80 ? 'Clean' : 'Refactoring recommended'} |
| **Reliability & Error Handling** | ${result.rating?.reliabilityScore ?? 0} / 100 | ${result.rating?.reliabilityScore >= 80 ? 'Robust' : 'Edge cases unhandled'} |
| **Google Cloud (GCP) Readiness** | ${result.rating?.gcpCloudScore ?? 0} / 100 | Cloud native alignment |

### Defect Distribution
- **Critical:** ${result.rating?.metrics?.criticalCount ?? 0}
- **High:** ${result.rating?.metrics?.highCount ?? 0}
- **Medium:** ${result.rating?.metrics?.mediumCount ?? 0}
- **Low:** ${result.rating?.metrics?.lowCount ?? 0}
- **Total Lines Analyzed:** ${result.rating?.metrics?.linesAnalyzed ?? 0}
- **Complexity Estimate:** ${result.rating?.metrics?.complexityEstimate || 'Moderate'}

---

## 3. Review Findings & Detected Issues (${result.issues?.length || 0} Total)

`;

  if (!result.issues || result.issues.length === 0) {
    md += `*No issues or security flaws were detected in this code artifact. Great work!*\n\n`;
  } else {
    result.issues.forEach((issue, index) => {
      md += `### ${index + 1}. [${issue.ruleCode || 'ISSUE'}] ${issue.title}\n\n`;
      md += `- **Severity:** ${severityBadge(issue.severity)}  \n`;
      md += `- **Category:** \`${issue.category}\`  \n`;
      md += `- **Lines Affected:** \`L${issue.lineStart} - L${issue.lineEnd}\`  \n`;
      md += `- **Impact:** ${issue.impact}  \n\n`;
      md += `**Description:**\n${issue.description}\n\n`;

      if (issue.codeSnippet) {
        md += `**Flagged Snippet:**\n\`\`\`${result.language || ''}\n${issue.codeSnippet}\n\`\`\`\n\n`;
      }

      if (issue.fixSuggestion) {
        md += `**Recommended Fix:**\n${issue.fixSuggestion}\n\n`;
      }

      if (issue.replacementSnippet) {
        md += `**Suggested Replacement:**\n\`\`\`${result.language || ''}\n${issue.replacementSnippet}\n\`\`\`\n\n`;
      }

      md += `---\n\n`;
    });
  }

  if (result.summary?.positiveNotes && result.summary.positiveNotes.length > 0) {
    md += `## 4. Positive Architectural Patterns\n\n`;
    result.summary.positiveNotes.forEach((note) => {
      md += `- ✅ ${note}\n`;
    });
    md += `\n---\n\n`;
  }

  if (result.neuralMeta) {
    md += `## 5. Neural AST & ML Pipeline Telemetry\n\n`;
    md += `- **Detected Language:** \`${result.neuralMeta.detectedLanguage}\` (${Math.round((result.neuralMeta.languageConfidence || 1) * 100)}% confidence)\n`;
    md += `- **Detection Mechanism:** \`${result.neuralMeta.detectionMethod}\`\n`;
    md += `- **Cognitive Controller:** \`${result.neuralMeta.controller}\`\n`;
    md += `- **Vector Dimensions:** \`${result.neuralMeta.tokenVectorDim || 512}-d\`\n`;
    md += `- **Security Defect Risk Vector:** \`${(result.neuralMeta.neuralDefectVectors?.securityRisk ?? 0).toFixed(2)}\`\n`;
    md += `- **Performance Defect Risk Vector:** \`${(result.neuralMeta.neuralDefectVectors?.performanceRisk ?? 0).toFixed(2)}\`\n`;
    md += `- **Maintainability Defect Risk Vector:** \`${(result.neuralMeta.neuralDefectVectors?.maintainabilityRisk ?? 0).toFixed(2)}\`\n\n`;
    md += `---\n\n`;
  }

  if (result.fullRefactoredCode) {
    md += `## 6. Suggested Full Refactored Code\n\n`;
    md += `\`\`\`${result.language || ''}\n${result.fullRefactoredCode}\n\`\`\`\n\n`;
    md += `---\n\n`;
  }

  md += `*Report generated automatically by the 24/7 Intelligent Code Reviewer on Google Cloud Platform.*`;

  return md;
}

/**
 * Triggers a client-side file download for structured report data
 */
export function downloadReport(
  result: CodeReviewResult, 
  format: 'json' | 'markdown'
): void {
  const sanitizedFilename = (result.filename || 'code-review')
    .replace(/[^a-zA-Z0-9._-]/g, '_');
  const timestamp = new Date(result.timestamp || Date.now())
    .toISOString()
    .slice(0, 19)
    .replace(/:/g, '-');

  let content: string;
  let filename: string;
  let mimeType: string;

  if (format === 'json') {
    // Generate structured audit report JSON
    const structuredAudit = {
      $schema: "https://cloud.google.com/review-standards/v1/audit-report.json",
      reportMetadata: {
        reportId: result.id,
        generatedAt: new Date().toISOString(),
        engine: "The 24/7 Intelligent Code Reviewer",
        components: [
          "ANN AST Feature Classifier",
          "Vertex AI Gemini Flash Lite",
          "Google Cloud Run Managed Pipeline"
        ],
        formatVersion: "1.2.0"
      },
      target: {
        filename: result.filename,
        language: result.language,
        branch: result.branch,
        prNumber: result.prNumber,
        commitHash: result.commitHash,
        author: result.author
      },
      verdict: result.rating?.verdict,
      scores: {
        overall: result.rating?.overallScore,
        letterGrade: result.rating?.letterGrade,
        security: result.rating?.securityScore,
        performance: result.rating?.performanceScore,
        maintainability: result.rating?.maintainabilityScore,
        reliability: result.rating?.reliabilityScore,
        cloudGCP: result.rating?.gcpCloudScore,
        defectCounts: result.rating?.metrics
      },
      executiveSummary: result.summary,
      issues: result.issues,
      neuralTelemetry: result.neuralMeta,
      refactoredCodeAvailable: Boolean(result.fullRefactoredCode)
    };

    content = JSON.stringify(structuredAudit, null, 2);
    filename = `code-review-${sanitizedFilename}-${timestamp}.json`;
    mimeType = 'application/json;charset=utf-8';
  } else {
    // Markdown format
    content = generateMarkdownReport(result);
    filename = `code-review-${sanitizedFilename}-${timestamp}.md`;
    mimeType = 'text/markdown;charset=utf-8';
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
